//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicPartsProject.Models.DBElectronicPartsModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_ElectronicPartsEntities : DbContext
    {
        public DB_ElectronicPartsEntities()
            : base("name=DB_ElectronicPartsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<file> files { get; set; }
        public virtual DbSet<supplier_parts> supplier_parts { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<part> parts { get; set; }
    }
}
