//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicPartsProject.Models.DBElectronicPartsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public int file_id { get; set; }
        public Nullable<int> part_id { get; set; }
        public string file_name { get; set; }
        public byte[] file_data { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
        public string file_type { get; set; }
    
        public virtual part part { get; set; }
    }
}
