//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicPartsProject.Models.DBElectronicPartsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public part()
        {
            this.files = new HashSet<file>();
            this.supplier_parts = new HashSet<supplier_parts>();
        }
    
        public int part_id { get; set; }
        public string part_number { get; set; }
        public int category_id { get; set; }
        public string description { get; set; }
        public string component_value { get; set; }
        public string footprint { get; set; }
        public string pkg_code { get; set; }
        public string schematic_symbol_file { get; set; }
        public string value { get; set; }
        public bool is_active { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplier_parts> supplier_parts { get; set; }
    }
}
