//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicPartsProject.Models.DBElectronicPartsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_parts
    {
        public int part_id { get; set; }
        public int supplier_id { get; set; }
        public string manufacturer_part_number { get; set; }
        public int supplier_part_id { get; set; }
    
        public virtual supplier supplier { get; set; }
        public virtual part part { get; set; }
    }
}
